# Generated by Django 5.1.2 on 2024-10-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
