# Generated by Django 5.1.2 on 2024-11-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_assigned_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_email',
        ),
    ]
