# Generated by Django 5.1.2 on 2024-11-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_assigned_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_email',
            field=models.EmailField(blank=True, help_text='Email of the assignee', max_length=254, null=True),
        ),
    ]
